importing the libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data collection and preprocessing

In [2]:
#loading the csv data to a pandas dataframe
data=pd.read_csv('HEART_DISEASE.csv')

In [3]:
#print 5 rows
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  slope  thal  \
0   69    1   0       160   234    1        2      131      0      1     0   
1   69    0   0       140   239    0        0      151      0      0     0   
2   66    0   0       150   226    0        0      114      0      2     0   
3   65    1   0       138   282    1        2      174      0      1     0   
4   64    1   0       110   211    0        2      144      1      1     0   

   target  
0       0  
1       0  
2       0  
3       1  
4       0

In [5]:
#no. of rows and colunms in a dataset
data.shape

(1927, 12)

In [6]:
#getting some info about data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1927 entries, 0 to 1926
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1927 non-null   int64
 1   sex       1927 non-null   int64
 2   cp        1927 non-null   int64
 3   trestbps  1927 non-null   int64
 4   chol      1927 non-null   int64
 5   fbs       1927 non-null   int64
 6   restecg   1927 non-null   int64
 7   thalach   1927 non-null   int64
 8   exang     1927 non-null   int64
 9   slope     1927 non-null   int64
 10  thal      1927 non-null   int64
 11  target    1927 non-null   int64
dtypes: int64(12)
memory usage: 180.8 KB


In [7]:
data.duplicated().sum()

1025

In [8]:
data=data.drop_duplicates()

In [9]:
data.duplicated().sum()

0

In [10]:
data['cp'].unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [11]:
data['thal'].unique()

array([0, 2, 1, 3, 6, 7], dtype=int64)

In [12]:
data['fbs'].unique()

array([1, 0], dtype=int64)

In [13]:
data['chol'].unique()

array([234, 239, 226, 282, 211, 227, 233, 240, 270, 288, 273, 204, 283,
       193, 186, 298, 213, 264, 244, 199, 231, 182, 269, 302, 245, 246,
       195, 281, 208, 221, 284, 319, 236, 261, 232, 294, 250, 262, 342,
       309, 325, 201, 205, 271, 266, 229, 197, 160, 308, 263, 219, 220,
       295, 203, 198, 235, 306, 157, 192, 210, 265, 254, 274, 277, 564,
       212, 278, 417, 360, 335, 313, 252, 243, 185, 318, 178, 218, 230,
       224, 340, 168, 126, 256, 258, 214, 304, 267, 196, 222, 175, 188,
       149, 275, 255, 257, 253, 177, 141, 242, 315, 209, 180, 268, 321,
       215, 174, 322, 286, 299, 237, 223, 228, 225, 248, 303, 407, 330,
       187, 164, 394, 260, 307, 166, 207, 206, 293, 305, 326, 249, 176,
       216, 259, 300, 276, 289, 241, 131, 354, 184, 409, 217, 353, 327,
       200, 311, 169, 290, 341, 247, 172, 167, 183], dtype=int64)

In [14]:
data['trestbps'].unique()

array([160, 140, 150, 138, 110, 170, 145, 134, 178, 120, 118, 152, 125,
       148, 156, 128, 136, 130, 124, 154, 135, 132, 108, 192, 101, 105,
       112, 126, 122, 180, 115, 146, 155, 102, 172, 100,  94, 129, 142,
       144, 106, 117, 158, 174, 164, 114, 165, 200, 123, 104], dtype=int64)

In [15]:
data['thalach'].unique()

array([131, 151, 114, 174, 144, 155, 150, 145, 171, 159, 125, 162, 190,
       178, 132, 182, 121, 143, 120, 179, 103, 140, 164, 160, 152, 141,
       169, 153, 163, 161, 166, 156, 195, 172, 158, 184, 168, 180, 175,
       138, 170, 173, 188, 192, 202, 116, 130, 112, 146, 115, 157, 148,
       133,  97, 137,  96, 134, 165, 154, 142, 147, 167, 123, 149, 139,
       126, 194, 187, 109, 108, 129,  71, 127, 122, 105, 136,  99, 106,
        90, 111, 124,  88, 117, 113,  95, 186, 128, 118, 185, 177, 181],
      dtype=int64)

In [16]:
data['exang'].unique()

array([0, 1], dtype=int64)

In [17]:
data['restecg'].unique()

array([2, 0, 1], dtype=int64)

In [18]:
data['slope'].unique()

array([1, 0, 2, 3], dtype=int64)

In [19]:
#checking for mising values
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
slope       0
thal        0
target      0
dtype: int64

In [20]:
#statastical measures
data.describe()

age         sex          cp    trestbps        chol         fbs  \
count  902.000000  902.000000  902.000000  902.000000  902.000000  902.000000   
mean    54.466741    0.679601    2.094235  131.661863  246.844789    0.147450   
std      9.035539    0.466889    1.334670   17.621935   51.785546    0.354751   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    1.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    2.000000  130.000000  241.500000    0.000000   
75%     61.000000    1.000000    3.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang       slope        thal      target  
count  902.000000  902.000000  902.000000  902.000000  902.000000  902.000000  
mean     0.837029  149.592018    0.327051    1.203991    2.629712    0.648559  
std      0.893337   22.881053    0.469396    0.751222    2.066144    0.845169  
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000  133.000000    0.000000    1.000000    2.000000    0.000000  
50%      1.000000  153.000000    0.000000    1.000000    2.000000    0.000000  
75%      2.000000  166.000000    1.000000    2.000000    3.000000    1.000000  
max      2.000000  202.000000    1.000000    3.000000    7.000000    4.000000

In [21]:
#checking the distibution of target variable
data['target'].value_counts()

0    462
1    356
2     36
3     35
4     13
Name: target, dtype: int64

1 represents defective heart

0 represents healthy heart

splitting the features and target

In [22]:
X=data.drop(columns='target',axis=1)
Y=data['target']

In [23]:
print(X)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  slope  thal
0      69    1   0       160   234    1        2      131      0      1     0
1      69    0   0       140   239    0        0      151      0      0     0
2      66    0   0       150   226    0        0      114      0      2     0
3      65    1   0       138   282    1        2      174      0      1     0
4      64    1   0       110   211    0        2      144      1      1     0
...   ...  ...  ..       ...   ...  ...      ...      ...    ...    ...   ...
1922   45    1   1       110   264    0        0      132      0      2     7
1923   68    1   4       144   193    1        0      141      0      2     7
1924   57    1   4       130   131    0        0      115      1      2     7
1925   57    0   2       130   236    0        2      174      0      2     3
1926   38    1   3       138   175    0        0      173      0      1     3

[902 rows x 11 columns]


In [24]:
print(Y)

0       0
1       0
2       0
3       1
4       0
       ..
1922    1
1923    2
1924    3
1925    1
1926    0
Name: target, Length: 902, dtype: int64


splitting the data into training and testing data

In [116]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.005,random_state=2)

In [117]:
print(X.shape,X_train.shape,X_test.shape)

(902, 11) (897, 11) (5, 11)


model training

Logistic regression

In [118]:
model=LogisticRegression()

In [119]:
#training the LR model wth training data
model.fit(X_train,Y_train)

C:\Users\VADDADI SINDHU\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

model evaluation

accuracy score

In [120]:
#accuracy for training data
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [122]:
#accuracy for testing data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [123]:
print("accuracy on testing data:",test_data_accuracy)

accuracy on testing data: 0.8


building a predictive system

In [33]:
print("enter details")
a=int(input("enter your age:"))
b=int(input("Gender(Male-1,Female-0):"))
c=int(input("chest pain type(0=typical angina\n1= atypical angina\n2=non—anginal pain\n3=asymptotic):"))
d=int(input("Resting bloodpressure(in mmHg):"))
e=int(input("cholestrol(mg/dl ):"))
f=int(input("fasting blood sugar>120mg/dl(true-1,false-0):"))
g=int(input("resting ecg(normal-0\n1 = having ST-T wave abnormality\n2 = left ventricular hyperthrophy)"))
h=int(input("Max heart rate achieved:"))
i=int(input("Exercise induced angina(1 = yes,0 = no):"))
j=int(input("Peak exercise ST segment(0 = upsloping,1 = flat,2 = downsloping):"))
k=int(input("thalassemia(1=normal,2=fixed defect,3=reversible defect):"))

prediction=model.predict([[a,b,c,d,e,f,g,h,i,j,k]])
print(prediction)

if(prediction==0):
    print("the person does not have a heart disease")
else:
    print("the person has heart disease")


enter details
enter your age:57
Gender(Male-1,Female-0):1
chest pain type(0=typical angina
1= atypical angina
2=non—anginal pain
3=asymptotic):1
Resting bloodpressure(in mmHg):120
cholestrol(mg/dl ):352
fasting blood sugar>120mg/dl(true-1,false-0):1
resting ecg(normal-0
1 = having ST-T wave abnormality
2 = left ventricular hyperthrophy)1
Max heart rate achieved:174
Exercise induced angina(1 = yes,0 = no):1
Peak exercise ST segment(0 = upsloping,1 = flat,2 = downsloping):1
thalassemia(1=normal,2=fixed defect,3=reversible defect):2
[0]
the person does not have a heart disease
